@startuml
(*) -right-> "Генерация здания"

if "Ввод" then
-right->[вручную] "Ручной ввод"
-down-> "Количество\n этажей и лифтов"
-left-> "Генерация\n пассажиров"
else
-->[рандомно] "Генерация\n пассажиров"
endif

if "Ввод" then
-left->[вручную] "Ввод:\n этаж/количество"
-->"Меню выбора\n действия"
    if "действие" then
    -->[добавить] "Ввод:\n этаж/количество"
    else
    -right->[эмуляция] "Эмуляция работы\n лифта"
    endif
else
-->[рандом] "Эмуляция работы\n лифта"
endif

-down-> "Меню выбора действия"

if "действие" then
-left->[добавить] "Ввод:\n этаж/количество"
else
-right->[выход] (*)
endif
@enduml
